version: "3.9"

services:
  minio:
    container_name: minio
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
      - MINIO_SERVER_REDIRECT_URL=${MINIO_SERVER_REDIRECT_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server --console-address :9001 /data
    networks:
      - siberiana-network

volumes:
  minio_data:
    external: true

networks:
  siberiana-network:
    external: true
