version: "3.9"

services:
  siberiana_minio:
    container_name: siberiana_minio
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
      - MINIO_SERVER_REDIRECT_URL=${MINIO_SERVER_REDIRECT_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server --console-address :9001 /data
    networks:
      - siberiana-network

  create_minio_buckets:
    container_name: create_minio_buckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set storage http://siberiana_minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      buckets=('default' 'artifacts' 'art' 'books');

      for bucket in $${buckets[@]}; do
      /usr/bin/mc mb --ignore-existing storage/$${bucket};
      /usr/bin/mc anonymous set download storage/$${bucket};
      done;

      exit 0;
      "
    networks:
      - siberiana-network

volumes:
  minio_data:
    external: true

networks:
  siberiana-network:
    external: true
